Move sketch to an appropriately named folder
The Arduino IDE requires that a sketch be located in a folder of the same name. When opening a file that does not meet this requirement the Arduino IDE presents a dialog:

The file "Slider.ino" needs to be inside a sketch folder named "WiFiUartTransparentBridge".
Create this folder, move the file, and continue?

After clicking "OK" the Arduino IDE currently moves only the file Slider.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:

C:\Users\UTILIS~1\AppData\Local\Temp\ccBOb1Vt.ltrans0.ltrans.o: In function `main':

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/main.cpp:43: undefined reference to `setup'

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/main.cpp:46: undefined reference to `loop'

The alternate solution of changing the sketch name to match the repository name is inferior because it is common for people to use GitHub's "Clone or Download > Download ZIP" feature to download sketches, rather than doing a Git clone and GitHub appends the branch/tag/commit to the downloaded folder name, which will cause the folder to still not match the sketch name.